#!/usr/bin/env bash

if [ "$(uname)" == "Darwin" ]; then
  curl -O -L https://github.com/biensoftware/september/releases/latest/download/september-macos && \
  mv september-macos september && \
  chmod +x bruno
else
  curl -O -L https://github.com/biensoftware/september/releases/latest/download/september-linux && \
  mv september-linux september && \
  chmod +x september
fi

while [[ "$#" -gt 0 ]]; do
  case $1 in
    -g|--global) global="true"; shift ;;
  esac
  shift
done

if [ "$global" == "true" ]; then
  sudo mv september /usr/local/bin/september
fi
