#!/usr/bin/env bash

if [ "$(uname)" == "Darwin" ]; then
  curl -O -L https://github.com/biensoftware/september/releases/latest/download/september-macos && \
  mv september-macos september && \
  chmod +x bruno
else
  curl -O -L https://github.com/biensoftware/september/releases/latest/download/september-linux && \
  mv september-linux september && \
  chmod +x september
fi

sudo mv september /usr/local/bin/september
